### ISSUE TITLE
mfa support

### ISSUE THREAD

**Issue by hinjo** [detunized/1password-sharp#1]
When mfa is activated in 1Password login fails with a "401 Unauthorized". After some digging around in you code I found that the error occurs in the below method at the **"var accountInfo = GetAccountInfo(sessionKey, jsonHttp)"** call.

But if I specify the wrong password the error occurs a bit earlier, in **"var session = StartNewSession(clientInfo, jsonHttp)"** call.

I tried to find out if there is some extra header with the otp that I could add but did not succeed, yet. Great c# wrapper otherwise, would just love to be able to do mfa aswell with it.

internal static Vault[] OpenAllVaults(ClientInfo clientInfo, IHttpClient http)
        {
            var keychain = new Keychain();
            var jsonHttp = MakeJsonClient(http, GetApiUrl(clientInfo.Domain));

            // Step 1: Request to initiate a new session
            var session = StartNewSession(clientInfo, jsonHttp);

            // After a new session has been initiated, all the subsequent requests must be
            // signed with the session ID.
            jsonHttp = MakeJsonClient(jsonHttp, session.Id);

            // Step 2: Perform SRP exchange
            var sessionKey = Srp.Perform(clientInfo, session, jsonHttp);

            // Assign a request signer now that we have a key.
            // All the following requests are expected to be signed with the MAC.
            jsonHttp.Signer = new MacRequestSigner(session, sessionKey);

            // Step 3: Verify the key with the server
            VerifySessionKey(clientInfo, session, sessionKey, jsonHttp);

            try
            {
                // Step 4: Get account info. It contains users, keys, groups, vault info and other stuff.
                //         Not the actual vault data though. That is requested separately.
                var accountInfo = GetAccountInfo(sessionKey, jsonHttp);

                // Step 5: Get all the keysets in one place. The original code is quite hairy around this
                //         topic, so it's not very clear if these keysets should be merged with anything else
                //         or it's enough to just use these keys. For now we gonna ignore other keys and
                //         see if it's enough.
                var keysets = GetKeysets(sessionKey, jsonHttp);

                // Step 6: Derive and decrypt keys
                DecryptAllKeys(accountInfo, keysets, clientInfo, keychain);

                // Step 7: Get and decrypt vaults
                var vaults = GetVaults(accountInfo, sessionKey, keychain, jsonHttp);

                // Done
                return vaults;
            }
            catch(Exception e)  //hinjo add
            {
                throw e;
            }
            finally
            {
                // TODO: If SignOut throws an exception it will hide the exception
                //       thrown in the try block above (if any). This will hide the
                //       original problem and thus will make it harder to diagnose
                //       the issue.

                // Last step: Make sure to sign out in any case
                SignOut(jsonHttp);
            }
        }

**Comment by detunized** [comment]
I'm working on merging all my password manager libraries into one big one. It's located here https://github.com/detunized/password-manager-access. 1Password module there has MFA support added. Please check it out.

**Comment by detunized** [comment]
I'm working on merging all my password manager libraries into one big one. It's located here https://github.com/detunized/password-manager-access. 1Password module there has MFA support added. Please check it out.

**Comment by detunized** [comment]
https://github.com/detunized/password-manager-access is also available on NuGet to make things easier.

**Comment by hinjo** [comment]
> https://github.com/detunized/password-manager-access is also available on NuGet to make things easier.


Okey, I will definitely check it out. Keep up the great work :)
